In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import warnings

warnings.filterwarnings("ignore", "use_inf_as_na")

In [2]:
df_kicks1 = pd.read_csv("continuous_kick_data_I.csv")
display(df_kicks1)

time        ax        ay        az        am        rx        ry  \
0       0.000005 -0.967285  0.018799  0.232910  0.993857  3.448486  3.631592   
1       0.342938 -0.970947  0.046387  0.266113  1.005671  3.997803  2.105713   
2       0.362382 -0.965332  0.064941  0.248047  0.988421  2.716064  1.892090   
3       0.381505 -0.943604  0.056396  0.244385  0.984302  3.997803  2.777100   
4       0.400617 -0.972900  0.059082  0.247803  1.016512  5.950928  1.922607   
...          ...       ...       ...       ...       ...       ...       ...   
8703  150.371564 -0.753662  0.292480  0.605225  1.020959  0.122070  2.288818   
8704  150.388793 -0.785400  0.310547  0.597656  1.012895  0.762939  0.823975   
8705  150.406081 -0.741943  0.302979  0.584229  0.990466  2.532959  2.044678   
8706  150.423288 -0.738525  0.321045  0.584961  0.999407  2.105713  2.471924   
8707  150.440651 -0.753662  0.319092  0.573730  0.975444  0.000000  1.617432   

            rz        rm  
0    -0.671387  5.211005  
1    -0.457764  4.283998  
2     0.061035  3.610631  
3    -0.457764  5.022066  
4    -1.098633  6.351470  
...        ...       ...  
8703 -1.159668  1.905333  
8704 -7.781982  1.385444  
8705 -0.305176  3.671000  
8706 -0.518799  2.759606  
8707 -0.488281  1.708439  

[8708 rows x 9 columns]

# Times of kicks (kicks 1)
- front - 9.34
- mid - 16.58
- front - 26.01
- low - 36.39
- mid - 46.69
- low - 56.86
- front - 70.94
- mid - 81.33
- front - 90.93
- front - 104.22
- low - 112.57
- mid - 121.36
- low - 129.13
- mid - 136.82
- low - 144.61

In [3]:
# Label Continuous Kick data 1
# Label 3 seconds either side of each time stamp as the kick
# Label data outside of these ranges as "no kick"


# Creating a movement column and initialise to 0
df_kicks1["movement"] = 0
# Creating a label mapping
label_mapping = {0: "no kick", 1: "front kick", 2: "low roundhouse kick", 3: "mid roundhouse kick"}

time_mapping = {9.34: 1, 16.58: 3, 26.01: 1, 36.39: 2, 46.69: 3, 56.86: 2, 70.94: 1, 81.33: 3, 90.93: 1, 104.22: 1, 112.57: 2, 121.36: 3, 129.13: 2, 136.82: 3, 144.61: 2}

# Looping through df and adding labels to data 
kick_times = list(time_mapping.keys())

# for row in df_kicks1.iterrows():
#     # min_time = row[1]["time"] - 3
#     # max_time = row[1]["time"] + 3
#     for time in kick_times:
#         min_time = time - 3
#         max_time = time + 3
#         if min_time <= row[1]["time"] <= max_time:
#             # print(row[1]["time"])
#             # print(f"min time {min_time}")
#             # print(f"max time {max_time}")
#             # row[1]["movement"] = time_mapping[time]
#             df_kicks1.at[row[0], "movement"] = time_mapping[time]
#             print(row[0])
#             # break
#         # break
#     # break
for row in df_kicks1.iterrows():
    for time in kick_times:
        min_time = time - 4
        max_time = time
        if min_time <= row[1]["time"] <= max_time:
            df_kicks1.at[row[0], "movement"] = time_mapping[time]

display(df_kicks1)


time        ax        ay        az        am        rx        ry  \
0       0.000005 -0.967285  0.018799  0.232910  0.993857  3.448486  3.631592   
1       0.342938 -0.970947  0.046387  0.266113  1.005671  3.997803  2.105713   
2       0.362382 -0.965332  0.064941  0.248047  0.988421  2.716064  1.892090   
3       0.381505 -0.943604  0.056396  0.244385  0.984302  3.997803  2.777100   
4       0.400617 -0.972900  0.059082  0.247803  1.016512  5.950928  1.922607   
...          ...       ...       ...       ...       ...       ...       ...   
8703  150.371564 -0.753662  0.292480  0.605225  1.020959  0.122070  2.288818   
8704  150.388793 -0.785400  0.310547  0.597656  1.012895  0.762939  0.823975   
8705  150.406081 -0.741943  0.302979  0.584229  0.990466  2.532959  2.044678   
8706  150.423288 -0.738525  0.321045  0.584961  0.999407  2.105713  2.471924   
8707  150.440651 -0.753662  0.319092  0.573730  0.975444  0.000000  1.617432   

            rz        rm  movement  
0    -0.671387  5.211005         0  
1    -0.457764  4.283998         0  
2     0.061035  3.610631         0  
3    -0.457764  5.022066         0  
4    -1.098633  6.351470         0  
...        ...       ...       ...  
8703 -1.159668  1.905333         0  
8704 -7.781982  1.385444         0  
8705 -0.305176  3.671000         0  
8706 -0.518799  2.759606         0  
8707 -0.488281  1.708439         0  

[8708 rows x 10 columns]

In [4]:
df_kicks1["movement"].unique()

array([0, 1, 3, 2], dtype=int64)

In [34]:
np_array = np.load("input_df.npy")
np_array

array([[[-1.9678997e+01],
        [ 3.2135372e+00],
        [ 1.4245423e+00],
        ...,
        [-1.9439915e-01],
        [ 3.9092288e-03],
        [-3.5519786e-02]]], dtype=float32)

In [5]:
df_kicks1.to_csv("continuous_kicks_I_labelled2.csv", index=False)

# Times of kicks (kicks 2)
- 'low' - 8.28
- 'front' - 17.61
- 'mid', - 26.36
- 'mid', - 41.75
- 'low', - 51.34
- 'front' - 59.94
- 'low', - 71.39
- 'front', - 80.7
- 'front', - 88.34
- 'low', - 99.97
- 'low', - 108.47
- 'mid', - 118.17
- 'front', - 128.42
- 'mid', - 137.01
- 'mid' - 145.38

In [6]:
df_kicks2 = pd.read_csv("continuous_kick_data_II.csv")


# Creating a movement column and initialise to 0
df_kicks2["movement"] = 0
# Creating a label mapping
label_mapping = {0: "no kick", 1: "front kick", 2: "low roundhouse kick", 3: "mid roundhouse kick"}

time_mapping = {8.28: 2, 17.61: 1, 26.36: 3, 41.75: 3, 51.34: 2, 59.94: 1, 71.39: 2, 80.7: 1, 88.34: 1, 99.97: 2, 108.47: 2, 118.17: 3, 128.42: 1, 137.01: 3, 145.38: 3}

# Looping through df and adding labels to data 
kick_times = list(time_mapping.keys())

# for row in df_kicks2.iterrows():
#     for time in kick_times:
#         min_time = time - 3
#         max_time = time + 3
#         if min_time <= row[1]["time"] <= max_time:
#             df_kicks2.at[row[0], "movement"] = time_mapping[time]
for row in df_kicks2.iterrows():
    for time in kick_times:
        min_time = time - 4
        max_time = time
        if min_time <= row[1]["time"] <= max_time:
            df_kicks2.at[row[0], "movement"] = time_mapping[time]
display(df_kicks2)


time        ax        ay        az        am        rx        ry  \
0       0.000006 -0.973877 -0.020752  0.231201  1.004236 -1.525879 -7.812500   
1       0.345907 -0.941650 -0.011475  0.268311  0.986162 -1.800537  0.823975   
2       0.365329 -0.935791 -0.006104  0.284668  0.974538 -5.035400  1.037598   
3       0.384484 -0.927490 -0.019287  0.308350  0.981418 -4.943848  1.983643   
4       0.403690 -0.949707 -0.042725  0.292480  0.999021 -3.295898  1.586914   
...          ...       ...       ...       ...       ...       ...       ...   
8769  151.534676 -0.944824  0.117920  0.332764  1.004489  1.190186  2.227783   
8770  151.551873 -0.924805  0.123291  0.321045  0.985200  1.037598  2.929688   
8771  151.569103 -0.966553  0.130615  0.325928  1.005844 -0.152588  2.807617   
8772  151.586268 -0.929443  0.122803  0.329834  0.994202 -0.213623  2.746582   
8773  151.603488 -0.925781  0.109131  0.340576  0.997759  0.213623  2.380371   

            rz        rm  movement  
0    -0.152588  1.267858         0  
1     0.427246  3.030935         0  
2     1.007080  5.403594         0  
3     1.007080  4.848359         0  
4     0.091553  3.084541         0  
...        ...       ...       ...  
8769 -0.854492  3.135301         0  
8770 -0.488281  3.049926         0  
8771 -0.274658  2.513952         0  
8772 -0.549316  2.730599         0  
8773 -0.579834  2.271459         0  

[8774 rows x 10 columns]

In [7]:
df_kicks2["movement"].unique()

array([0, 2, 1, 3], dtype=int64)

In [8]:
df_kicks2.to_csv("continuous_kicks_II_labelled2.csv", index=False)

# Times of kicks (kicks 3)
- low - 9.45
- mid - 18.45
- front - 26.71
- low - 35.48
- low - 44.57
- front - 52.92
- low - 62.6
- front - 73.03
- mid - 82.49
- front - 90.85
- mid - 100.97
- mid - 111.91
- mid - 126.76 !!!! Possibly need to push this back as I pressed lap late
- low - 137.39
- front - 147.51

In [9]:
df_kicks3 = pd.read_csv("continuous_kick_data_III.csv")


# Creating a movement column and initialise to 0
df_kicks3["movement"] = 0
# Creating a label mapping
label_mapping = {0: "no kick", 1: "front kick", 2: "low roundhouse kick", 3: "mid roundhouse kick"}

time_mapping = {9.45: 2, 18.45: 3, 26.71: 1, 35.48: 2, 44.57: 2, 52.92: 1, 62.6: 2, 73.03: 1, 82.49: 3, 90.85: 1, 100.97: 3, 111.91: 3, 126.76: 3, 137.39: 2, 147.51: 1}

# Looping through df and adding labels to data 
kick_times = list(time_mapping.keys())

# for row in df_kicks3.iterrows():
#     for time in kick_times:
#         min_time = time - 3
#         max_time = time + 3
#         if min_time <= row[1]["time"] <= max_time:
#             df_kicks3.at[row[0], "movement"] = time_mapping[time]
for row in df_kicks3.iterrows():
    for time in kick_times:
        min_time = time - 4
        max_time = time
        if min_time <= row[1]["time"] <= max_time:
            df_kicks3.at[row[0], "movement"] = time_mapping[time]
display(df_kicks3)


time        ax        ay        az        am        rx        ry  \
0       0.000006 -0.993408  0.027588  0.069336  0.997258 -0.854492  1.922607   
1       0.345716 -0.986084  0.015137  0.071533  0.987100 -0.915527  2.593994   
2       0.364990 -0.982178  0.031006  0.068604  0.989475  0.976562  2.197266   
3       0.384142 -0.979248  0.015625  0.037354  0.985420  1.342773  2.777100   
4       0.403385 -0.978271  0.037354  0.069092  0.985169  0.732422  2.990723   
...          ...       ...       ...       ...       ...       ...       ...   
9112  157.276149 -0.977295  0.080566  0.147217  0.988574  0.122070  2.014160   
9113  157.293291 -0.972900  0.076416  0.152344  0.991101  0.549316  2.319336   
9114  157.310528 -0.988037  0.072998  0.143311  1.001748  0.732422  1.586914   
9115  157.327724 -0.974609  0.077637  0.144287  0.985746  1.068115  1.831055   
9116  157.344908 -0.978027  0.082275  0.152100  0.997381  1.342773  2.105713   

            rz        rm  movement  
0     0.244141  2.449404         0  
1     0.244141  2.798480         0  
2    -0.305176  2.653450         0  
3    -0.885010  3.157500         0  
4    -0.396729  3.216530         0  
...        ...       ...       ...  
9112  0.732422  2.390522         0  
9113  0.579834  2.573086         0  
9114  0.427246  1.997911         0  
9115  0.274658  2.309880         0  
9116  0.183105  2.408376         0  

[9117 rows x 10 columns]

In [10]:
df_kicks3["movement"].value_counts()

movement
0    5634
2    1161
3    1161
1    1161
Name: count, dtype: int64

In [11]:
df_kicks3.to_csv("continuous_kicks_III_labelled2.csv", index=False)

# Times of kicks (testing)
- front - 9.55
- front - 18.2
- front - 28.81
- front - 39.41
- front - 47.29
- mid - 63.51
- mid - 71.43
- mid - 81.79
- mid - 92.42
- mid - 102.43
- low - 113.55
- low - 121.4
- low - 126.95
- low - 134.73
- low - 147.97

In [12]:
df_kicks_test = pd.read_csv("continuous_kick_data_test.csv")


# Creating a movement column and initialise to 0
df_kicks_test["movement"] = 0
# Creating a label mapping
label_mapping = {0: "no kick", 1: "front kick", 2: "low roundhouse kick", 3: "mid roundhouse kick"}

time_mapping = {9.55: 1, 18.2: 1, 28.81: 1, 39.41: 1, 47.29: 1, 63.51: 3, 71.43: 3, 81.79: 3, 92.42: 3, 102.43: 3, 113.55: 2, 121.4: 2, 126.95: 2, 134.73: 2, 147.97: 2}

# Looping through df and adding labels to data 
kick_times = list(time_mapping.keys())

for row in df_kicks_test.iterrows():
    for time in kick_times:
        min_time = time - 4
        max_time = time
        if min_time <= row[1]["time"] <= max_time:
            df_kicks_test.at[row[0], "movement"] = time_mapping[time]

display(df_kicks_test)

time        ax        ay        az        am        rx        ry  \
0       0.000006 -0.989990  0.024902  0.080078  0.996284 -1.770020  1.647949   
1       0.347414 -0.979492  0.037842  0.077637  0.993011 -2.685547  1.770020   
2       0.366726 -0.993896  0.026855  0.078125  0.989820 -3.662109  1.068115   
3       0.385210 -0.977539  0.006592  0.080811  0.977003 -2.838135  1.770020   
4       0.402500 -0.984131 -0.002686  0.086914  0.988363 -1.770020  1.525879   
...          ...       ...       ...       ...       ...       ...       ...   
8987  155.322249 -0.956299  0.160400  0.160889  0.982999 -1.892090  1.861572   
8988  155.339453 -0.963135  0.184814  0.168213  0.993196 -3.417969  2.288818   
8989  155.356724 -0.968994  0.137451  0.184082  0.992604 -3.051758  1.464844   
8990  155.373898 -0.966309  0.125244  0.174561  0.996825 -2.319336  1.373291   
8991  155.391228 -0.962891  0.119385  0.163818  0.976950 -1.525879  1.678467   

            rz        rm  movement  
0    -0.366211  2.781791         0  
1     0.396729  2.996633         0  
2     0.152588  3.817870         0  
3     0.488281  3.122352         0  
4    -0.091553  2.082811         0  
...        ...       ...       ...  
8987  0.915527  3.181009         0  
8988  1.190186  4.181131         0  
8989  1.464844  3.619261         0  
8990  1.373291  2.667627         0  
8991  0.793457  2.522089         0  

[8992 rows x 10 columns]

In [13]:
df_kicks_test["movement"].value_counts()

movement
0    5514
1    1161
2    1159
3    1158
Name: count, dtype: int64

In [14]:
df_kicks_test.to_csv("continuous_kicks_test_labelled2.csv", index=False)

In [5]:
import random
kicks3 = ['front', 'front', 'front', 'front', 'front', 'mid', 'mid', 'mid', 'mid', 'mid', 'low', 'low', 'low', 'low', 'low']
# random.shuffle(kicks3)
# print(kicks3)
for kick in kicks3:
    print(kick)

front
front
front
front
front
mid
mid
mid
mid
mid
low
low
low
low
low
